Improves the readability of the output from jats2epub. Also jats2epub no longer expects to find xmlcalabash, kindlegen and epubcheck in the programs subfolder of the jats2epub root folder.
Instead those commands are expected to be avaliable from the path in any folder.

If installing those programs in the path is difficult, instead use jats2epub-legacy
and make sure xmlcalabash, kindlegen and epubcheck are installed in the programs
subfolder of the jats2epub root folder.

diff --git a/jats2epub b/jats2epub
--- a/jats2epub
+++ b/jats2epub
@@ -6,6 +6,8 @@
 #	This script relies on the XProc pipeline process-jats.xpl to do the xml
 #	transformation work. This bash script takes care of all the steps that couldn't 
 #	be implemented in the XProc pipeline process-jats.xpl alone.
+#	
+#	It requires java and calabash to be installed on the system, or it will exit.
 #
 #	Author: 
 #
@@ -39,9 +41,7 @@ function displayUsage {
 	echo "Usage: ./jats2epub xmlfile [required] assetfolder [optional]"
 	echo ""
 	echo "Available switches:"
-	echo "   -h,   --help					Display Help/Troubleshooting"
-	echo "   -i,   --install-info				Display how to install components used by this script"
-	echo "   -o,   --operation				Display how the script operates"
+	echo "   -h,   --help			Display Help/Troubleshooting"
 	echo ""
 	echo "Examples"
 	echo "   To process \"article.xml\" in the \"xml-source folder\":"
@@ -50,140 +50,93 @@ function displayUsage {
 	echo "   To process \"article.xml\" in the \"xml-source folder\" and also copy images from \"xml-source/article-extras/images\" into epub-structure:"
 	echo "   (2)	./jats2epub xml-source-folder/article.xml xml-source-folder/article-extras"
 	echo ""
-	echo "   Display Help/Troubleshooting/Install-info:"
-	echo "   (3)	./jats2epub			Display this usage"
+	echo "Display Help/Troubleshooting/Install-info:"
+	echo "   (3)	./jats2epub		Display this usage"
 	echo "   (4)	./jats2epub -h		Display Help/Troubleshooting"
-	echo "   (5)	./jats2epub -i		Display how to install components used by this script"
-	echo "   (6)	./jats2epub -o		Display how to the script operates"
 
 }
 
-function displayOperation {
-	echo "### How the script Operates  ###"
-	echo ""
-	echo "(1) clear out existing contents of output-folder "
-	echo "(2) create output/epub folder"
-	echo "(3) copy contents of assets/epub-template into output/epub"
-	echo "(4) If a folder is supplied in 2.nd parameter, copy contents of this folder to output/epub/OEBPS"
-	echo "(5) Attempt to process the source xml article with the XProc pipeline \"process-jats-xml.xpl\" with the following command:"
-	echo "	calabash -i source=[path-to-xml-source-article] process-jats-xml.xpl"
-	echo ""
-	echo "If all goes well the output_working/epub folder is correctly populated and can be made into an ePub"
-	echo "This script will then attempt to pack the ePub by using zip-commands."
-	echo ""
-	echo "(6) Creating a zip archive with the same name as the xml-file, excluding the extension and adding a timestamp and the \".epub\" extension"
-	echo "(7) Adding mimetype to this archive with no compression"
-	echo "(8) Adding the rest of the files inside output/epub to the archive with higher compression"
-	echo "(9) Moving the created epub from output/epub to two directories up (should be the dir you are running the script from)"
-	echo ""
-	echo "(10) Call epubcheck to validate the newly created epub"
-
-}
-
-function displayInstallInfo {
-	echo "### Installing components used by this script  ###"
-	echo ""
-	echo "   The versions mentioned here are the ones current at the time of writing (dec 2013)."
-	echo "   You might have to adjust to newer versions in the future"
-	echo ""
-	echo "XML Calabash - XProc processor used to process the pipeline. [MUST HAVE]."
-	echo "   XML Calabash can be downloaded from at http://xmlcalabash.com/download/"
-	echo "   At the time of writing http://xmlcalabash.com/download/calabash-1.0.15-94.jar is the version used."
-	echo ""
-	echo "   Get XMLCalabash:"
-	echo "      wget http://xmlcalabash.com/download/calabash-1.0.15-94.jar"
-	echo "   Install (need root access to install system wide, but can also be installed in a user's home dir):"
-	echo "      java -jar calabash-1.0.15-94.jar"
-	echo ""
-	echo "Epubcheck - Utility to validate epubs. Used by the script to validate produced epub. [GOOD TO HAVE]"	 
-	echo "   Find it at http://code.google.com/p/epubcheck/, or download directly: "
-	echo ""
-	echo "   Get epubcheck:"
-	echo "      wget http://epubcheck.googlecode.com/files/epubcheck-3.0.1.zip"
-	echo "      unzip epubcheck-3.0.1.zip"
-	echo ""
-	echo "   System wide installation requires root access:"
-	echo "      sudo cp -r epubcheck-3.0.1 /usr/local/"
-	echo "      sudo ln -s /usr/local/epubcheck-3.0.1/ /usr/local/epubcheck"
-	echo ""
-	echo "   Create a shellscript to simplify running epubcheck and put it in /usr/local/bin:"
-	echo "      printf \"#\"! > epubcheck && printf \"/bin/bash\n\" >> epubcheck && echo \"java -jar /usr/local/epubcheck/epubcheck-3.0.1.jar \\\$1\" >> epubcheck"
-	echo "      chmod +x epubcheck && sudo chown root epubcheck && sudo mv epubcheck /usr/local/bin"
-	echo ""
-
-}
 
 function displayHelp {
-	echo "### Help/Troubleshooting  ###"
+	echo""
+	echo "jats2epub help/troubleshooting"
 	echo ""
 	echo "This is a script to automate ePub creation from an article tagged and validated against the NISO JATS 1.0 XML tagset"
 	echo ""
 	echo "To begin with, the input xml-file needs to be tagged according to the JATS1.0 tagset and validated against jats xsd or DTD."
-	echo "The first parameter is required: the xml-file to be processed"
-	echo "If no images are used in the article, you only need to use the 1st parameter"
 	echo ""
-	echo "Example"
-	echo "	./jats2epub xml-source/article.xml"
+	echo "The first parameter to the script is required: the xml-file to be processed"
+	echo "If no images or extra files are used in the article or needed in the epub, you only need to use the first parameter"
 	echo ""
-	echo "The second parameter is optional: a folder. It must be used if the article contains images to be copied inside the epub"
-	echo "It should be the parent folder of a \"images\"-folder where the images are placed."
+	echo "Example 1"
 	echo ""
-	echo "Example"
+	echo "(1)	./jats2epub xml-source/article.xml"
+	echo ""
+	echo "The second parameter is optional: a folder. It must be used if the article contains images or other files or folders to be copied inside the epub"
+	echo ""
+	echo "Example 2"
+	echo ""
 	echo "Article is located at this path:"
 	echo "	/home/username/xml-source/article01.xml"
+	echo ""
 	echo "Images are located at this path:"
-	echo "	/home/username/xml-source/article01/images/figure01.png"
-	echo "	/home/username/xml-source/article01/images/figure02.png"
-	echo "	/home/username/xml-source/article01/images/figure03.png"
-	echo "To process article01.xml and include all images you would run this command:"
-	echo "	./jats2epub /home/username/xml-source/article.xml /home/username/xml-source/article01"
+	echo "	/home/username/xml-source/article_extras/images/figure01.png"
+	echo "	/home/username/xml-source/article_extras/images/figure02.png"
+	echo "	/home/username/xml-source/article_extras/images/figure03.png"
+	echo ""
+	echo "To process article01.xml and also copy the \"images\" folder as well as any other files or folders in article_extras/ to the epub:"
+	echo ""
+	echo "(2)	./jats2epub /home/username/xml-source/article.xml /home/username/xml-source/article_extras"
 	echo ""
 	echo "You don't have to use absolute paths, you can use relative paths as well."
 	echo ""
 }
 
 function ePubValidation {
-	if [ -f programs/epubcheck-3.0.1/epubcheck-3.0.1.jar ]
-	then
+	if command -v epubcheck >/dev/null; then
+        	echo "NOTICE: Found epubcheck - validating $epubname:"
 		echo ""
-		echo "Validating $epubname with epubcheck:"
+		echo "NOTICE: epubcheck output BEGIN"
 		echo ""
-		java -jar programs/epubcheck-3.0.1/epubcheck-3.0.1.jar output_final/$epubname
+		epubcheck output_final/$epubname
 		echo ""
-		echo "If epubcheck returned no errors, it means the generated ePub passed validation check."
-		echo "You still need open it with an ePub reader (calibre for instance) to see if it is as you expected."
+		echo "NOTICE: epubcheck output END"
 		echo ""
-		echo "If epubcheck returned with errors, try to fix them and rerun this script"
-		echo ""
+
 	else
-		echo ""
-		echo "NOTICE: Validation attempt unsuccessful! Can't find programs/epubcheck-3.0.1/epubcheck-3.0.1.jar"
+        	echo "WARNING: epubcheck not found - skipping .epub validation!"
 		echo ""
 	fi
 }
 
 function mobiGen {
-	if [ -f programs/kindlegen/kindlegen ]
-	then
-		echo "Trying to generate kindle .mobi with kindlegen:"
-		programs/kindlegen/kindlegen output_final/$epubname -o $mobiname
+	if command -v kindlegen >/dev/null; then
+        	echo "NOTICE: Found kindlegen - trying to generate .mobi version:"
+		echo ""
+		echo "NOTICE: kindlegen output BEGIN"
+		kindlegen output_final/$epubname -o $mobiname
+		echo ""
+		echo "NOTICE: kindlegen output END"
 		echo ""
 	else
-		echo "NOTICE: kindlegen is not installed. If you want added .mobi functionality, please see programs/kindlegen/README-kindlegen.txt"
+	        echo "WARNING: kindlegen not found - skipping .mobi creation!"
 		echo ""
 	fi
 }
 
 # main 'program'
+# check if java is installed - print error and exit if not found
+command -v java >/dev/null 2>&1 || { echo "FATAL ERROR: JAVA runtime not found - Please install a java runtime environment and try again." >&2; exit 1; }
+
+# check if calabash is installed - print error and exit if not found
+command -v calabash >/dev/null 2>&1 || { echo "FATAL ERROR: calabash not found - Please install calabash and try again." >&2; exit 1; }
+
 # check if there is one or two  parameters
+
 if [ "$#" = "1" ] || [ "$#" = "2" ]; then
 	filepath=$1
-	if [ $1 == "-o" ] || [ $1 == "--operation" ]; then
-		displayOperation
-	elif [ $1 == "-h" ] || [ $1 == "--help" ]; then
+	if [ $1 == "-h" ] || [ $1 == "--help" ]; then
 		displayHelp
-	elif [ $1 == "-i" ] || [ $1 == "--install-info" ]; then
-		displayInstallInfo
 	elif [ -f "$filepath" ]
 	then
 		dirname=${filepath%/*}
@@ -196,11 +149,13 @@ if [ "$#" = "1" ] || [ "$#" = "2" ]; then
 		pdfname=$filename_base$timestamp.pdf
 		htmlname=$filename_base$timestamp.html
 		echo ""
-		echo "Clearing old contents of output_working .."
+		echo "NOTICE: Clearing old contents of output_working/"
 		rm -rf output_working/*
-		echo "Creating folders (if they don't exist): output_working/epub ..."
+		echo ""
+		echo "NOTICE: Creating folders (if they don't exist): output_working/epub/"
 		mkdir -p output_working/epub/
-		echo "Copying over epub-template from assets/epub-template to output_working/epub/ ..."
+		echo ""
+		echo "NOTICE: Copying over epub-template from assets/epub-template to output_working/epub/"
 		cp -r assets/epub-template/* output_working/epub/
 		# copying assets for one article
 		# should I check this before running?
@@ -209,28 +164,43 @@ if [ "$#" = "1" ] || [ "$#" = "2" ]; then
 			echo "cp -r $resources/* output_working/epub/OEBPS"
 			cp -r $resources/* output_working/epub/OEBPS
 		fi
-		echo "Processing \"$filename\" in \"$dirname\" with \"process-jats-xml.xpl\" (XProc pipeline) using XML Calabash ..."
+		echo ""
+		echo "NOTICE: Starting XProc pipeline processing using XML Calabash"
+		echo ""
+		echo "        Processing \"$filename\" in \"$dirname\" with the pipeline \"process-jats-xml.xpl\""
+		echo ""
+		echo "NOTICE: XML Calabash output BEGIN"
 		echo ""
 		calabash -i source=$filepath process-jats-xml.xpl
 		echo ""
-		echo "If the processing went well, you will see <c:result ...>...</c:result> elements above, one for each created file, if not, calabash will output error messages."
+		echo "NOTICE: XML Calabash output END"
 		echo ""
-		echo "Creating $epubname (packing contents of output_working/epub with zip)..."
+		echo "NOTICE: If the XProc processing went well, the XML Calabash output will contain a"
+		echo "        <c:result>...</c:result> element with the location of each file created by the pipeline."
+		echo "        If not, the XML Calabash output will contain error messages to help you troubleshoot."
+		echo ""
+		echo "NOTICE: Packing contents of output_working/epub/ with zip to $epubname"
 		cd output_working/epub
 		zip -0Xq $epubname mimetype
 		zip -Xr9Dq $epubname *
+		echo ""
+		echo "NOTICE: Moving $epubname to output_final/"
 		mv $epubname ../../output_final/
 		cd ../../
 		echo ""
-		echo "Moving web-version of article to output_final/$htmlname"
+		echo "NOTICE: Moving html-version of article to output_final/$htmlname"
 		echo ""
 		mv output_working/article-webversion.html output_final/$htmlname
 		ePubValidation
 		mobiGen
-		echo "DONE! Script has completed."
-		echo "Please check messages output from the script as well as created files in output_final and output_working."
+		echo "NOTICE: DONE! Script has completed."
+		echo "        Please check the script output as well as files created in the folders output_final/ and output_working/"
+		echo ""
+
 	else
-		echo "Error: The file '$filepath' was not found."
+		echo ""
+		echo "ERROR: The file '$filepath' was not found."
+		echo ""
 		displayUsage
 	fi
 else 
